### ISSUE TITLE
陈硕的模板编译报错Undefined control sequence

### ISSUE THREAD

**Issue by allanruin** [soulmachine/acm-cheat-sheet#19]
出错语句包括`\include`，也有部分是中文内容标识为上述错误。

![typeset_problem_01](https://cloud.githubusercontent.com/assets/1366627/9021018/4ab99366-3860-11e5-83e0-03deced3fe23.png)

**Comment by soulmachine** [comment]
你是用我的那个虚拟机编译的吗？

**Comment by allanruin** [comment]
嗯，latex小白，后来发觉这些报错都并不影响编译，囧。陈硕的模板貌似进行了调整，然后标题位置错乱了，我自己摸索了一阵搞定了。我关掉这个issu好了。

**Comment by soulmachine** [comment]
你的出错信息还是属于错误的，虽然能正常编译出PDF，但是肯定有某些地方错乱。不过你解决了就好 了:)
