### ISSUE TITLE
百度网盘链接已经失效

### ISSUE THREAD

**Issue by GH1995** [soulmachine/acm-cheat-sheet#22]
是否可以把需要的字体重传一下，或者直接给出列表？

**Comment by soulmachine** [comment]
感谢指出，已经更新了链接

**Comment by GH1995** [comment]
**Adobe中文字体**
- AdobeFangsongStd-Regular.otf
- AdobeHeitiStd-Regular.otf
- AdobeKaitiStd-Regular.otf
- AdobeSongStd-Light.otf

**Latin Modern Mono**
- lmmono10-italic.otf
- lmmono10-regular.otf
- lmmono12-regular.otf
- lmmono8-regular.otf
- lmmono9-regular.otf

**Linux Libertine**
- LinLibertine_I.ttf
- LinLibertine_Mah.ttf
- LinLibertine_RBIah.ttf
- LinLibertine_RBah.ttf
- LinLibertine_RIah.ttf
- LinLibertine_RZIah.ttf
- LinLibertine_RZah.ttf
- LinLibertine_Rah.ttf

**Nimbus Sans L**
- ufonts.com_nimbus_sans_l_regular.ttf

**PT Sans Narrow**
- PTN57F.ttf
- PTN77F.ttf

**Times New Roman**
- times.ttf
- timesbd.ttf
- timesbi.ttf
- timesi.ttf

**URW Gothic L**
- urw-gothic-l-book-oblique.ttf
- urw-gothic-l-book.ttf
- urw-gothic-l-demi-oblique.ttf
- urw-gothic-l-demi.ttf

**URW Palladio L**
- urw-palladio-l-bold-italic.ttf
- urw-palladio-l-bold.ttf
- urw-palladio-l-italic.ttf
- urw-palladio-l-roman.ttf
